#!/usr/bin/env python3
r"""instance-recipe.py — what it takes to stand up ONE estate on this engine, derived from the code (paul-asked 2026-09-03).

    python3 tools/instance-recipe.py            # rewrites INSTANCE-RECIPE.md (the § Refinement log is preserved)
    python3 tools/instance-recipe.py --check    # exit 1 if INSTANCE-RECIPE.md is not what the code says today

Paul: "a very clear picture of what is dynamic versus what's generated… how do we systematically recreate this
view, what data do we need to input, and what do we have to turn on and off — a process we will work through
again when we build out Bob's, so document it and keep refining it." Everything below is READ from the build and
the viewer, never typed: identity keys from build-viewer.IDENTITY, modules from momlib.MODULES, canon files from
momlib.DOMAINS + the renderer's PROPERTY_DATA reads, placeholders from the template, Worker vars from wrangler.toml.
"""
import argparse, importlib.util, json, os, re, sys

HERE = os.path.dirname(os.path.abspath(__file__)); ROOT = os.path.dirname(HERE)
sys.path.insert(0, HERE)
import momlib  # noqa: E402
OUT = os.path.join(ROOT, "INSTANCE-RECIPE.md")
LOG_START, LOG_END = "<!-- refinement-log:start -->", "<!-- refinement-log:end -->"


def _mod(name):
    spec = importlib.util.spec_from_file_location(name, os.path.join(HERE, name + ".py")); m = importlib.util.module_from_spec(spec); spec.loader.exec_module(m); return m


def build():
    bv = _mod("build-viewer")
    viewer = open(os.path.join(ROOT, "viewer.html"), encoding="utf-8").read()
    template = open(bv.TEMPLATE, encoding="utf-8").read()
    fern = json.load(open(bv.DEFAULT_INSTANCE))
    toml = open(os.path.join(ROOT, "worker", "wrangler.toml"), encoding="utf-8").read()
    vars_ = sorted(set(re.findall(r"^([A-Z_]+) = \"", toml, re.M)))
    secrets = sorted(set(re.findall(r"env\.([A-Z_]+_KEY|ANTHROPIC_API_KEY|GITHUB_TOKEN|SHARED_TOKEN|AMBIENT_APP_KEY|AMBIENT_API_KEY|AIRNOW_API_KEY|OPENAI_API_KEY)", open(os.path.join(ROOT, "worker", "worker.js"), encoding="utf-8").read()))) 
    placeholders = sorted(set(re.findall(r"\{\{[A-Z_]+(?::[A-Za-z_]+)?\}\}", template)))
    prose = sorted(set(re.findall(r'data-record-prose="([^"]+)"', viewer)))
    site = sorted(set(re.findall(r"data-site=['\"]([A-Za-z]+)['\"]", viewer)))
    prop_reads = sorted(set(re.findall(r"PROPERTY_DATA\.([a-zA-Z]+)", viewer)) | set(re.findall(r"\bp\.(story|sky|intros|resources|microclimate|soils|climate|hardiness|frostDates|location|property|utilities)\b", viewer)))
    module_els = sorted(set(re.findall(r'id="([a-z-]+)"[^>]*data-module="([a-z-]+)"', viewer)) | set((b, a) for a, b in re.findall(r'data-module="([a-z-]+)"[^>]*id="([a-z-]+)"', viewer)))
    L = []
    L.append("# INSTANCE RECIPE — what it takes to stand up one estate on this engine\n")
    L.append("> **GENERATED by `tools/instance-recipe.py` from the code — do not hand-edit above the refinement log.** Regenerate after any change to `build-viewer.py`, `momlib.MODULES`, `wrangler.toml`, or a `data-module` / `data-record-prose` attribute; `--check` in the session-start block says when it is stale. The § Refinement log at the bottom is hand-kept and survives regeneration.\n")
    L.append("Paul, 2026-09-03: *\"a very clear picture of what is dynamic versus what's generated… how do we systematically recreate this view, what data do we need to input, and what do we have to turn on and off — a process we will work through again when we build out Bob's.\"*\n")
    L.append("## 1 · Three kinds of thing, and where each lives\n")
    L.append("| kind | what it is | where an instance supplies it | how it reaches the page |\n|---|---|---|---|")
    L.append("| **IDENTITY** — names you choose | the place's display name, tagline, tile subtitle, station name | `instance/<estate>.json` → `identity` | filled at BUILD into %d template sites (static HTML, no runtime fill) |" % len([p for p in placeholders if p.startswith("{{IDENTITY")]))
    L.append("| **MODULES** — what you switch on | named bundles of the record (garden · motor-pool · equipment · house-systems · wildlife · place) + renderer switches (weather) | `estate.json` → `modules` (`on` · `on-minimal` · `off` · `declared-absent`; a missing key is OFF and a finding) | `ESTATE_MODULES` const at build; every `[data-module]` element and the jump strip follow it at load; Python consumers via `momlib.enabled_domains()` |")
    L.append("| **CANON** — the record itself | the JSON files a module's domains read, `property.json`'s sections, `RELEASE_NOTES.md` | the instance's canon directory (`instance.canon`), declared absences in `instance.absent` | inlined at BUILD as `*_DATA` consts (an absent file → an empty const of the right shape); prose read at LOAD via `data-record-prose` / `data-site`; Worker digest built from the same files |")
    L.append("| **DEPLOYMENT** — where it runs | estate id, legacy window, station MAC, allowed hosts, QA budget | `worker/wrangler.toml` `[vars]` per env + Worker secrets | Worker bindings; `/health` reports them |")
    L.append("\n## 2 · Identity keys (`instance/<estate>.json` → `identity`)\n")
    L.append("| key | Fernwood's value | derived how |\n|---|---|---|")
    for k, fn in bv.IDENTITY.items():
        try: val = fn(fern["identity"], json.load(open(os.path.join(ROOT, "property.json"))))
        except Exception as e: val = "(error: %s)" % e
        L.append("| `%s` | %s | `build-viewer.IDENTITY[%r]` |" % (k, str(val).replace("|", "\\|")[:80], k))
    L.append("\nInstance identity keys in use: %s. Absent → `undeclared` / defaults (`station` builds as `undeclared`, loudly)." % ", ".join("`%s`" % k for k in fern["identity"].keys()))
    L.append("\n## 3 · Modules (`estate.json` → `modules`) and what each switches\n")
    L.append("| module | members (domains) | groups / non-domain members | switches on the page |\n|---|---|---|---|")
    by_mod = {}
    for el, mod in module_els: by_mod.setdefault(mod, []).append(el)
    for name, spec in momlib.MODULES.items():
        extra = ", ".join(spec.get("groups", ())) or ", ".join(spec.get("non_domain_members", {}).keys())
        L.append("| `%s` — %s | %s | %s | %s |" % (name, spec.get("what", ""), ", ".join(spec["members"]), extra or "—", ", ".join("`#%s`" % e for e in sorted(by_mod.get(name, []))) or "(python consumers only)"))
    for name, why in momlib.NON_DOMAIN_MODULES.items():
        L.append("| `%s` — %s | — | renderer switch | %s |" % (name, why.split(" (")[0], ", ".join("`#%s`" % e for e in sorted(by_mod.get(name, []))) or "—"))
    L.append("\nFernwood's block: %s. Condo (paper model): garden · motor-pool · equipment · wildlife OFF, house-systems ON, place on-minimal, neighbourhood declared-absent." % json.dumps(momlib.modules_of()))
    L.append("\n## 4 · Canon an instance must supply (or declare absent)\n")
    L.append("| module | canon file | list key | viewer const | if absent |\n|---|---|---|---|---|")
    for dtype, dom in momlib.DOMAINS.items():
        mods = [m for m, sp in momlib.MODULES.items() if dtype in sp["members"]]
        L.append("| %s | `%s` | `%s` | `%s` | declare `%s` in `instance.absent` → empty const, card hides where it reads the module |" % ("/".join(mods), dom.file, dom.key, dom.const, dom.file.split(".")[0]))
    L.append("| garden (non-domain) | `turf.json` | `sources` | `TURF_DATA` | declare absent |")
    L.append("| — | `references.json` | whole document | `REFERENCES_DATA` | declare absent → the References card hides |")
    L.append("| — | `RELEASE_NOTES.md` | parsed, latest 5 | `RELEASE_NOTES_DATA` | no file → `[]` → the card hides |")
    L.append("| — | `property.json` | whole document | `PROPERTY_DATA` | REQUIRED — the place itself |")
    L.append("\n**`property.json` sections the page reads** (each is optional except `property` and `location`; a missing section omits its panel): %s." % ", ".join("`%s`" % k for k in prop_reads))
    L.append("\n**Prose filled from the record at load** (`data-record-prose`): %s. **Derived words** (`data-site`): %s." % (", ".join("`%s`" % p for p in prose), ", ".join("`%s`" % s_ for s_ in site)))
    L.append("\n## 5 · Built vs runtime — the placeholders in `engine/viewer.template.html`\n")
    L.append("%d placeholders: %s" % (len(placeholders), " · ".join("`%s`" % p for p in placeholders)))
    L.append("\nEverything else in the template is ENGINE and must name no place — the falsifier (`tools/check-condo-falsifier.py`) counts 14 Fernwood strings in the engine half and holds at 0.")
    L.append("\n## 6 · Deployment inputs (the Worker)\n")
    L.append("`wrangler.toml` vars per environment: %s. Secrets (set through `/secrets`, never a file): %s." % (", ".join("`%s`" % v for v in vars_), ", ".join("`%s`" % s_ for s_ in secrets) or "see worker.js"))
    L.append("\n## 7 · The proof a new instance renders as itself\n")
    L.append("```\npython3 tools/build-viewer.py --instance <instance.json> --out <scratch>/viewer.html   # builds, fails loud on an undeclared absence\npython3 tools/check-condo-falsifier.py                                            # engine untouched · 0 identity strings · module switch reaches the build\npython3 -m http.server 8766 & python3 tools/qa-walk.py http://127.0.0.1:8766/<scratch>/viewer.html   # boots · her viewport · no script error\npython3 tools/uniqueness-ledger.py <fernwood-url> <new-url>                       # what the two share (boilerplate?) vs what is theirs\n```")
    L.append("\n## 8 · What we learned standing up the second estate (2026-09-03, the condo paper model)\n")
    L.append("- The engine half carried ~115 place-naming literals; each became identity (build), canon (record) or a derived read. The falsifier is the measurement, per string.\n- Three renderer throws on missing canon (valley/airport note · aspect block · coordinates) — every optional section now guards itself.\n- Six location fetches called their APIs with `undefined`; an estate with no coordinates now fetches nothing.\n- The station is three-state (present · declared-absent · undeclared); declared-absent labels the card regional with no error dot.\n- Release notes and the references card were Fernwood's on the condo — both are per-instance now, and a card with nothing to show hides.\n- The two estates wore ONE colour scheme (`identity.theme` is not built yet) and shared 47 sentences that speak of a place — the uniqueness ledger tracks both.")
    return "\n".join(L) + "\n"


def render(existing):
    log = ""
    if existing and LOG_START in existing and LOG_END in existing:
        log = existing[existing.index(LOG_START):existing.index(LOG_END) + len(LOG_END)]
    if not log:
        log = LOG_START + "\n\n## Refinement log — hand-kept, survives regeneration\n\n- 2026-09-03 — first written, from the condo pass. Next revisit: Bob's house (the third estate, first one outside the family). Questions to carry: does `identity.theme` land before or with Bob? which of the 47 shared sentences become canon prose vs engine copy? does a family door (C4) change what `estate.json` must declare?\n\n" + LOG_END
    return build() + "\n" + log + "\n"


if __name__ == "__main__":
    ap = argparse.ArgumentParser(); ap.add_argument("--check", action="store_true"); a = ap.parse_args()
    existing = open(OUT, encoding="utf-8").read() if os.path.exists(OUT) else ""
    new = render(existing)
    if a.check:
        if existing == new: print("✅ INSTANCE-RECIPE.md matches the code."); sys.exit(0)
        print("🔴 INSTANCE-RECIPE.md is STALE — regenerate: python3 tools/instance-recipe.py"); sys.exit(1)
    open(OUT, "w", encoding="utf-8").write(new); print("wrote %s (%d bytes)" % (os.path.relpath(OUT, ROOT), len(new)))
