#!/usr/bin/env python3
"""
review-pending-species.py — Phase F gatekeeper tool.

Pulls Garden Guru's suggested plant/animal additions from the Worker's
pending-species KV queue and prints a markdown digest for Paul to review.
Supports promote (writes a starter entry to plants.json or the appropriate
animal JSON) and dismiss (deletes the KV entry).

Stdlib only — no pip install. Idempotent (re-running with --list is safe).

Usage:
    # 1. Review the queue
    python3 tools/review-pending-species.py --list --days 30

    # 2. Inspect a specific suggestion in detail
    python3 tools/review-pending-species.py --show <id>

    # 3. Promote a suggestion to the curated canon
    python3 tools/review-pending-species.py --promote <id>

    # 4. Dismiss a suggestion (drop from queue)
    python3 tools/review-pending-species.py --dismiss <id>

Credentials come from env vars (same as tools/analyze-fernwood.py):
    FERNWOOD_WORKER_URL    defaults to the production Worker URL
    FERNWOOD_TOKEN         required; matches the Worker's SHARED_TOKEN

Promotion behavior: writes a starter entry (id, name, scientificName, photo,
attribution-from-Mom note) into the relevant source JSON. The full Fernwood
schema (currentSeasonNote, care calendars, monthsPresent, etc.) is NOT
generated by this tool — Paul authors those fields when he integrates the
suggestion. After --promote, the next step is to manually fill those fields
and re-run wire-photos.py to inline the data into viewer.html.
"""

import argparse
import base64
import datetime as dt
import json
import os
import re
import sys
import urllib.parse
import urllib.request

# === Config =================================================================

DEFAULT_WORKER_URL = "https://tate-tracker.paul-kirschenbauer.workers.dev"
WORKER_URL = os.environ.get("FERNWOOD_WORKER_URL", DEFAULT_WORKER_URL).rstrip("/")
TOKEN = os.environ.get("FERNWOOD_TOKEN", "")
HTTP_TIMEOUT_SEC = 20
ROOT = os.path.abspath(os.path.join(os.path.dirname(__file__), ".."))

# Map suggestion kind → (json file, image dir, species_path)
KIND_TARGETS = {
    "plant": {
        "json_file": "plants.json",
        "image_dir": "images/plants",
        "species_path": "plants",
        "species_label": "plants",
    },
    "animal-mammal": {
        "json_file": "mammals.json",
        "image_dir": "images/mammals",
        "species_path": "species",
        "species_label": "mammals",
    },
    "animal-bird": {
        "json_file": "birds.json",
        "image_dir": "images/birds",
        "species_path": "species",
        "species_label": "birds",
    },
    "animal-amphibian": {
        "json_file": "amphibians.json",
        "image_dir": "images/amphibians",
        "species_path": "species",
        "species_label": "amphibians",
    },
    "animal-snake": {
        "json_file": "snakes.json",
        "image_dir": "images/snakes",
        "species_path": "species",
        "species_label": "snakes",
    },
    "animal-lizard": {
        "json_file": "lizards.json",
        "image_dir": "images/lizards",
        "species_path": "species",
        "species_label": "lizards",
    },
}


# === HTTP helpers ===========================================================


def _call(method, path, body=None):
    if not TOKEN:
        print("ERROR: FERNWOOD_TOKEN env var is not set.", file=sys.stderr)
        sys.exit(2)
    url = WORKER_URL + path
    data = None
    headers = {"X-Tate-Token": TOKEN, "Accept": "application/json"}
    if body is not None:
        data = json.dumps(body).encode("utf-8")
        headers["Content-Type"] = "application/json"
    req = urllib.request.Request(url, data=data, method=method, headers=headers)
    try:
        with urllib.request.urlopen(req, timeout=HTTP_TIMEOUT_SEC) as r:
            return json.loads(r.read().decode("utf-8"))
    except urllib.error.HTTPError as e:
        body_txt = e.read().decode("utf-8", errors="replace") if e.fp else ""
        print(f"ERROR: {method} {path} → HTTP {e.code}: {body_txt[:300]}", file=sys.stderr)
        sys.exit(3)


def fetch_range(days):
    end = dt.datetime.utcnow().date()
    start = end - dt.timedelta(days=days - 1)
    return _call("GET", f"/api/pending-species?start={start.isoformat()}&end={end.isoformat()}")


def fetch_all_records(days):
    data = fetch_range(days)
    days_dict = (data or {}).get("days") or {}
    records = []
    for date in sorted(days_dict.keys(), reverse=True):
        for r in days_dict[date] or []:
            r["_date"] = date
            records.append(r)
    return records


def find_record(rec_id, days=90):
    for r in fetch_all_records(days):
        if r.get("id") == rec_id:
            return r
    return None


def delete_record(rec_id):
    return _call("DELETE", f"/api/pending-species/{urllib.parse.quote(rec_id)}")


# === Render helpers =========================================================


def slugify(name):
    s = name.lower().strip()
    s = re.sub(r"[^a-z0-9\s-]", "", s)
    s = re.sub(r"\s+", "-", s)
    s = re.sub(r"-+", "-", s)
    return s.strip("-") or "unnamed"


def render_list(records):
    if not records:
        print("# Pending species\n\nQueue is empty.")
        return
    print(f"# Pending species — {len(records)} entry{'y' if len(records) == 1 else 'ies'}\n")
    by_date = {}
    for r in records:
        by_date.setdefault(r["_date"], []).append(r)
    for date in sorted(by_date.keys(), reverse=True):
        print(f"## {date}\n")
        for r in by_date[date]:
            kind = r.get("kind", "?")
            conf = r.get("confidence", "?")
            in_canon = "(in canon)" if r.get("inCanon") else "(NEW)"
            common = r.get("commonName", "?")
            sci = r.get("scientificName", "?")
            elev_fit = r.get("elevationFit") or ""
            habitat = r.get("habitatHint") or ""
            print(f"- **{common}** _({sci})_ — {kind} · {conf} confidence · {in_canon}")
            if elev_fit:
                print(f"  - Fit: {elev_fit}")
            if habitat:
                print(f"  - Habitat: {habitat}")
            print(f"  - `{r.get('id', '?')}`")
        print()


def render_show(rec):
    print(f"# {rec.get('commonName', '?')} — _{rec.get('scientificName', '?')}_\n")
    print(f"- **ID:** `{rec.get('id', '?')}`")
    print(f"- **Submitted:** {rec.get('submittedAt', '?')}")
    print(f"- **Kind:** {rec.get('kind', '?')}")
    print(f"- **Confidence:** {rec.get('confidence', '?')}")
    print(f"- **Elevation fit:** {rec.get('elevationFit') or '(none noted)'}")
    print(f"- **Habitat hint:** {rec.get('habitatHint') or '(none noted)'}")
    print(f"- **Already in curated canon:** {rec.get('inCanon')}")
    print(f"- **Conversation:** `{rec.get('conversationId', '?')}`")
    print(f"- **Device:** `{rec.get('deviceId', '?')}`")
    thumb = rec.get("thumbnail")
    if thumb:
        print(f"- **Thumbnail bytes:** {len(thumb)} chars (base64)")
        print("- **Tip:** to view, pipe the thumbnail into a file:")
        print(f"    python3 tools/review-pending-species.py --show {rec.get('id')} --dump-image /tmp/photo.jpg")


def dump_image(rec, path):
    thumb = rec.get("thumbnail") or ""
    if not thumb.startswith("data:"):
        print("ERROR: no inline image in this record.", file=sys.stderr)
        sys.exit(4)
    head, _, b64 = thumb.partition(",")
    raw = base64.b64decode(b64)
    with open(path, "wb") as f:
        f.write(raw)
    print(f"Wrote {len(raw)} bytes → {path}")


# === Promote / dismiss ======================================================


def resolve_target(rec):
    """Map a suggestion record to the source JSON / image dir to promote into.

    For animals, the record may carry kind="animal" without subtype — Paul
    decides by hand which species_label fits. The tool reads `kind` from the
    record and looks up KIND_TARGETS, prompting if kind=="animal" needs a
    subtype.
    """
    k = rec.get("kind")
    if k == "plant":
        return KIND_TARGETS["plant"]
    if k == "animal":
        # Animals are split across 5 JSONs; ask Paul.
        choices = [k for k in KIND_TARGETS if k.startswith("animal-")]
        print("This is an animal suggestion. Which group does it belong to?")
        for i, c in enumerate(choices, 1):
            print(f"  {i}. {c.replace('animal-', '')}")
        try:
            choice = int(input("Enter number: ").strip())
            return KIND_TARGETS[choices[choice - 1]]
        except (ValueError, IndexError, KeyboardInterrupt):
            print("Cancelled.", file=sys.stderr)
            sys.exit(5)
    print(f"ERROR: unknown kind '{k}' in record.", file=sys.stderr)
    sys.exit(6)


def promote(rec):
    target = resolve_target(rec)
    json_path = os.path.join(ROOT, target["json_file"])
    if not os.path.isfile(json_path):
        print(f"ERROR: target JSON not found at {json_path}", file=sys.stderr)
        sys.exit(7)
    with open(json_path, "r", encoding="utf-8") as f:
        data = json.load(f)

    # Walk into the species_path (dot path)
    container = data
    for part in target["species_path"].split("."):
        container = container[part]
    if not isinstance(container, list):
        print(f"ERROR: species_path '{target['species_path']}' did not resolve to a list.", file=sys.stderr)
        sys.exit(8)

    new_id = slugify(rec.get("commonName") or "")
    if any(s.get("id") == new_id for s in container):
        print(f"WARN: an entry with id '{new_id}' already exists in {target['json_file']}.")
        print("      The promotion will append a duplicate id — fix this before committing.")

    starter = {
        "id": new_id,
        "name": rec.get("commonName", ""),
        "scientificName": rec.get("scientificName", ""),
        "emoji": "📷",
        "_phaseF": {
            "suggestedAt": rec.get("submittedAt"),
            "confidence": rec.get("confidence"),
            "elevationFit": rec.get("elevationFit"),
            "habitatHint": rec.get("habitatHint"),
            "deviceId": rec.get("deviceId"),
            "conversationId": rec.get("conversationId"),
            "note": "Promoted from pending-species KV queue. Schema fields below are starter values; Paul to author the full Fernwood schema (currentSeasonNote, monthsPresent/Active, habitat, peakMonths, voice/notes, etc.) before this entry is considered curated.",
        },
        "TODO_complete_schema": True,
    }

    container.append(starter)
    with open(json_path, "w", encoding="utf-8") as f:
        json.dump(data, f, indent=2, ensure_ascii=False)
        f.write("\n")
    print(f"Wrote starter entry → {target['json_file']} as id '{new_id}'.")

    # If the suggestion includes a thumbnail, drop it at images/{cat}/{id}.jpg
    thumb = rec.get("thumbnail") or ""
    if thumb.startswith("data:image/"):
        head, _, b64 = thumb.partition(",")
        ext = "jpg"
        if "image/png" in head:
            ext = "png"
        elif "image/jpeg" in head or "image/jpg" in head:
            ext = "jpg"
        img_path = os.path.join(ROOT, target["image_dir"], f"{new_id}.{ext}")
        os.makedirs(os.path.dirname(img_path), exist_ok=True)
        with open(img_path, "wb") as f:
            f.write(base64.b64decode(b64))
        print(f"Wrote thumbnail → {os.path.relpath(img_path, ROOT)}")
    else:
        print("(no inline thumbnail to save)")

    print()
    print("Next steps:")
    print(f"  1. Edit {target['json_file']} — fill in the Fernwood-specific schema fields")
    print(f"     (remove the TODO_complete_schema flag once done)")
    print(f"  2. Run: python3 tools/wire-photos.py --category {target['species_label']}")
    print(f"     (re-inlines the {target['species_label'].upper()}_DATA const in viewer.html)")
    print(f"  3. Run: python3 tools/review-pending-species.py --dismiss {rec.get('id')}")
    print(f"     (removes the entry from the KV queue once promotion is committed)")


def dismiss(rec):
    res = delete_record(rec["id"])
    print(f"Dismissed: {rec['id']}")
    print(f"  Remaining on {rec['_date']}: {res.get('remaining_on_date', '?')}")


# === Entrypoint =============================================================


def main():
    ap = argparse.ArgumentParser(
        description="Review and triage Garden Guru's pending plant/animal suggestions.",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog=__doc__,
    )
    mode = ap.add_mutually_exclusive_group(required=True)
    mode.add_argument("--list", action="store_true", help="Print all pending suggestions as a markdown digest")
    mode.add_argument("--show", metavar="ID", help="Print full record for one suggestion")
    mode.add_argument("--promote", metavar="ID", help="Write a starter entry to the appropriate source JSON")
    mode.add_argument("--dismiss", metavar="ID", help="Delete a suggestion from the KV queue")
    ap.add_argument("--days", type=int, default=30, help="Look back N days (default 30)")
    ap.add_argument("--dump-image", metavar="PATH", help="With --show, write the thumbnail to PATH")
    args = ap.parse_args()

    if args.list:
        records = fetch_all_records(args.days)
        render_list(records)
        return

    target_id = args.show or args.promote or args.dismiss
    rec = find_record(target_id, days=args.days)
    if not rec:
        print(f"ERROR: no record found with id '{target_id}' within the last {args.days} days.", file=sys.stderr)
        sys.exit(1)

    if args.show:
        render_show(rec)
        if args.dump_image:
            dump_image(rec, args.dump_image)
    elif args.promote:
        promote(rec)
    elif args.dismiss:
        dismiss(rec)


if __name__ == "__main__":
    main()
